/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControladorJuego;
import javax.swing.JButton;
import model.Sonido;
import view.GUIJuego;


/**
 *
 * @author ellio
 */
public class GUIInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInicio.class.getName());

    /**
     * Creates new form GUIInicio
     */
    private  Sonido sonidos = new Sonido();
    public GUIInicio() {
        initComponents();
        sonidos.musicaFondo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnHistroia = new javax.swing.JButton();
        comboColor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/boton.png"))); // NOI18N
        btnJugar.setContentAreaFilled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, 90));

        btnCreditos.setBackground(new java.awt.Color(29, 47, 93));
        btnCreditos.setForeground(new java.awt.Color(255, 255, 255));
        btnCreditos.setText("Creditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 100, -1));

        btnInstrucciones.setBackground(new java.awt.Color(29, 47, 93));
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 110, 30));

        btnHistroia.setBackground(new java.awt.Color(29, 47, 93));
        btnHistroia.setForeground(new java.awt.Color(255, 255, 255));
        btnHistroia.setText("Historia");
        btnHistroia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistroiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistroia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 110, 30));

        comboColor.setBackground(new java.awt.Color(29, 47, 93));
        comboColor.setForeground(new java.awt.Color(255, 255, 255));
        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Amarillo", "Azul", "Verde" }));
        comboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColorActionPerformed(evt);
            }
        });
        getContentPane().add(comboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 90, 20));

        jLabel1.setBackground(new java.awt.Color(29, 47, 93));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione un color");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 20));

        imgFondo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        imgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/imgInicio_1.png"))); // NOI18N
        getContentPane().add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 503, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        GUICreditos creditos = new GUICreditos();
        creditos.setVisible(true);
        creditos.setLocationRelativeTo(null);
        this.setVisible(false);
        sonidos.click();
        sonidos.detenerFondo();
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        // TODO add your handling code here:
        GUICreditos creditos = new GUICreditos();
        creditos.setVisible(true);
        creditos.setLocationRelativeTo(null);
        this.setVisible(false);
        sonidos.click();
        sonidos.detenerFondo();
        
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void comboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColorActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        int idCombo = comboColor.getSelectedIndex();
        ControladorJuego ctr1 = new ControladorJuego(idCombo);
        GUIJuego v2 = new GUIJuego(ctr1);
        v2.setLocationRelativeTo(null);
        v2.setVisible(true);
        this.dispose();
        sonidos.click();
        sonidos.detenerFondo();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnHistroiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistroiaActionPerformed
        // TODO add your handling code here:
        GUICreditos creditos = new GUICreditos();
        creditos.setVisible(true);
        creditos.setLocationRelativeTo(null);
        this.setVisible(false);
        sonidos.click();
        sonidos.detenerFondo();
    }//GEN-LAST:event_btnHistroiaActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistroia;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
