/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


/**
 *
 * @author ellio
 */
public class GUIJuego extends javax.swing.JFrame {
    
    
    /**
     * Creates new form GUIJuego
     */
    public GUIJuego() {
        initComponents();

    }

    public PanelControl getPanelControl() {
        return panelControl;
    }

    public PanelTablero getPanelTablero() {
        return panelTablero;
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new view.PanelTablero();
        panelControl = new view.PanelControl();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 530));
        getContentPane().add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.PanelControl panelControl;
    private view.PanelTablero panelTablero;
    // End of variables declaration//GEN-END:variables

}
