/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;

/**
 *
 * @author ellio
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
        
    }//fin del constructor

    public void setImgTablero(JLabel imgTablero) {
        this.imgTablero = imgTablero;
    }

    public JLabel getImgFichaAmarillo() {
        return imgFichaAmarillo;
    }

    public void setImgFichaAmarillo(JLabel imgFichaAmarillo) {
        this.imgFichaAmarillo = imgFichaAmarillo;
    }

    public JLabel getImgFichaAzul() {
        return imgFichaAzul;
    }

    public void setImgFichaAzul(JLabel imgFichaAzul) {
        this.imgFichaAzul = imgFichaAzul;
    }

    public JLabel getImgFichaVerde() {
        return imgFichaVerde;
    }

    public void setImgFichaVerde(JLabel imgFichaVerde) {
        this.imgFichaVerde = imgFichaVerde;
    }

    public JLabel getLblFichaRoja() {
        return lblFichaRoja;
    }

    public void setLblFichaRoja(JLabel lblFichaRoja) {
        this.lblFichaRoja = lblFichaRoja;
    }

    public void moverFicha(int colorId, int x, int y) {
        JLabel lbl = labelJugador(colorId);
        if(lbl != null){
            lbl.setLocation(x , y);
            lbl.repaint();
            this.repaint();
        
        }
    }//fin del metodo

    public JLabel labelJugador(int colorId) {
        if (colorId == 0) {
            return lblFichaRoja;
        }
        if (colorId == 1) {
            return imgFichaAmarillo;
        }
        if (colorId == 2) {
            return imgFichaAzul;
        }
        return imgFichaVerde;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFichaRoja = new javax.swing.JLabel();
        imgFichaAzul = new javax.swing.JLabel();
        imgFichaVerde = new javax.swing.JLabel();
        imgFichaAmarillo = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(null);

        lblFichaRoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaRoja.png"))); // NOI18N
        add(lblFichaRoja);
        lblFichaRoja.setBounds(110, 90, 20, 40);

        imgFichaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaAzul.png"))); // NOI18N
        add(imgFichaAzul);
        imgFichaAzul.setBounds(430, 90, 21, 31);

        imgFichaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaVerde.png"))); // NOI18N
        add(imgFichaVerde);
        imgFichaVerde.setBounds(110, 420, 21, 31);

        imgFichaAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaAmarilla.png"))); // NOI18N
        add(imgFichaAmarillo);
        imgFichaAmarillo.setBounds(430, 420, 21, 32);

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/tablerografico.png"))); // NOI18N
        add(imgTablero);
        imgTablero.setBounds(10, 10, 500, 520);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFichaAmarillo;
    private javax.swing.JLabel imgFichaAzul;
    private javax.swing.JLabel imgFichaVerde;
    private javax.swing.JLabel imgTablero;
    private javax.swing.JLabel lblFichaRoja;
    // End of variables declaration//GEN-END:variables
}
