/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;



/**
 *
 * @author ellio
 */
public class PanelControl extends javax.swing.JPanel {
    

    /**
     * Creates new form PanelTablero
     */
    public PanelControl() {
        initComponents();
    }

    public JButton getBtnDado() {
        return btnDado;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }

    public void setLblFichaTurno(String texto) {
        lblFichaTurno.setText("Ficha turno "+texto);
    }

    public void setLblNumeroDado(int valor) {
        lblNumeroDado.setText("Numero dado: "+ valor);
    }

    public void setTxtPuntosJugador(int valor) {
        txtPuntosJugador.setText("Puntos Jugador: "+valor);
    }

    public void setTxtPuntosOponente(int valor) {
        txtPuntosOponente.setText("Puntos Oponente: "+valor);
    }

    public void setTxtTiempo(int valor) {
        txtTiempo.setText("Tiempo: "+valor);
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroDado = new javax.swing.JLabel();
        btnDado = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblFichaTurno = new javax.swing.JLabel();
        txtPuntosJugador = new javax.swing.JLabel();
        txtPuntosOponente = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumeroDado.setText("Numero dado:");
        add(lblNumeroDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        btnDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/DadoPF.png"))); // NOI18N
        btnDado.setBorderPainted(false);
        btnDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadoActionPerformed(evt);
            }
        });
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 139, 140));

        btnReinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/ReinicioProyectoFinal.png"))); // NOI18N
        btnReinicio.setBorderPainted(false);
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });
        add(btnReinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 100, 100));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/MenuPF.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 100));

        lblFichaTurno.setText("Ficha turno:");
        add(lblFichaTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 72, -1));

        txtPuntosJugador.setText("Puntos:");
        add(txtPuntosJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        txtPuntosOponente.setText("Puntos Oponente:");
        add(txtPuntosOponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, -1));

        txtTiempo.setText("Tiempo:");
        add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        GUIInicio v1 = new GUIInicio();
        v1.setVisible(true);
        v1.setLocationRelativeTo(v1);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDadoActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnReinicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel lblFichaTurno;
    private javax.swing.JLabel lblNumeroDado;
    private javax.swing.JLabel txtPuntosJugador;
    private javax.swing.JLabel txtPuntosOponente;
    private javax.swing.JLabel txtTiempo;
    // End of variables declaration//GEN-END:variables
}
