/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JLabel;
import model.TableroCoordenadas;

/**
 *
 * @author ellio
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    private TableroCoordenadas tablero;

    public PanelTablero() {
        initComponents();
    }//fin del constructor

    public JLabel getImgFichaAmarillo() {
        return imgFichaAmarillo;
    }

    public JLabel getImgFichaAzul() {
        return imgFichaAzul;
    }

    public JLabel getImgFichaRoja() {
        return imgFichaRoja;
    }

    public JLabel getImgFichaVerde() {
        return imgFichaVerde;
    }

    public void setTablero(TableroCoordenadas tablero) {
        this.tablero = tablero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgFichaRoja = new javax.swing.JLabel();
        imgFichaAzul = new javax.swing.JLabel();
        imgFichaVerde = new javax.swing.JLabel();
        imgFichaAmarillo = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(null);

        imgFichaRoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaRoja.png"))); // NOI18N
        add(imgFichaRoja);
        imgFichaRoja.setBounds(80, 100, 21, 31);

        imgFichaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaAzul.png"))); // NOI18N
        add(imgFichaAzul);
        imgFichaAzul.setBounds(400, 100, 21, 31);

        imgFichaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaVerde.png"))); // NOI18N
        add(imgFichaVerde);
        imgFichaVerde.setBounds(80, 420, 21, 31);

        imgFichaAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaAmarilla.png"))); // NOI18N
        add(imgFichaAmarillo);
        imgFichaAmarillo.setBounds(400, 420, 21, 32);

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/tablerografico.png"))); // NOI18N
        add(imgTablero);
        imgTablero.setBounds(0, 32, 500, 500);
    }// </editor-fold>//GEN-END:initComponents
    public void moverFicha(int colorId, int x, int y) {
        JLabel lbl = labelJugador(colorId);
        if (lbl != null) {
            lbl.setLocation(x, y);
            lbl.repaint();
            this.repaint();
        }
    }

    public JLabel labelJugador(int colorId) {
        if (colorId == 0) {
            return imgFichaRoja;
        }
        if (colorId == 1) {
            return imgFichaAmarillo;
        }
        if (colorId == 2) {
            return imgFichaAzul;
        }
        return imgFichaVerde;//3 verde
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFichaAmarillo;
    private javax.swing.JLabel imgFichaAzul;
    private javax.swing.JLabel imgFichaRoja;
    private javax.swing.JLabel imgFichaVerde;
    private javax.swing.JLabel imgTablero;
    // End of variables declaration//GEN-END:variables
}
