/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ellio
 */
public class PanelTablero extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
    }//fin del constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgFichaRoja = new javax.swing.JLabel();
        imgFichaAzul = new javax.swing.JLabel();
        imgFichaVerde = new javax.swing.JLabel();
        imgFichaAmarillo = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(null);

        imgFichaRoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaRoja.png"))); // NOI18N
        add(imgFichaRoja);
        imgFichaRoja.setBounds(80, 100, 21, 31);

        imgFichaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaAzul.png"))); // NOI18N
        add(imgFichaAzul);
        imgFichaAzul.setBounds(400, 100, 21, 31);

        imgFichaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaVerde.png"))); // NOI18N
        add(imgFichaVerde);
        imgFichaVerde.setBounds(80, 420, 21, 31);

        imgFichaAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/FichaAmarilla.png"))); // NOI18N
        add(imgFichaAmarillo);
        imgFichaAmarillo.setBounds(400, 420, 21, 32);

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/tablerografico.png"))); // NOI18N
        add(imgTablero);
        imgTablero.setBounds(0, 32, 500, 500);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFichaAmarillo;
    private javax.swing.JLabel imgFichaAzul;
    private javax.swing.JLabel imgFichaRoja;
    private javax.swing.JLabel imgFichaVerde;
    private javax.swing.JLabel imgTablero;
    // End of variables declaration//GEN-END:variables
}
