/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author ellio
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public PanelControl() {
        initComponents();

    }
    // --- GETTERS para que el controlador se suscriba a los botones ---

    public JButton getBtnDado() {
        return btnDado;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }

// --- SETTERS prácticos para mostrar info ---
    public void setNumeroDado(int valor) {
        lblNumeroDado.setText("Numero dado: " + valor);
    }

    public void setTextoTurno(String texto) {
        lblFichaTurno.setText("Ficha turno: " + texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroDado = new javax.swing.JLabel();
        btnDado = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblFichaTurno = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumeroDado.setText("Numero dado:");
        add(lblNumeroDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 140, -1));

        btnDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/DadoPF.png"))); // NOI18N
        btnDado.setBorderPainted(false);
        btnDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadoActionPerformed(evt);
            }
        });
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 139, 140));

        btnReinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/ReinicioProyectoFinal.png"))); // NOI18N
        btnReinicio.setBorderPainted(false);
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });
        add(btnReinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 100, 100));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImágenesProyectoFinal/MenuPF.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 100));

        lblFichaTurno.setText("Ficha turno:");
        add(lblFichaTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        GUIInicio v1 = new GUIInicio();
        v1.setVisible(true);
        v1.setLocationRelativeTo(v1);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDadoActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnReinicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel lblFichaTurno;
    private javax.swing.JLabel lblNumeroDado;
    // End of variables declaration//GEN-END:variables
}
